name: dbcopy
on: workflow_dispatch
jobs:
  dbcopy:
    runs-on: ubuntu-latest
    steps:
      - name: Run the clone
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/calltracking
            ./db_copy.sh
 
