name: deploy
on:
  push:
    branches: [ "live" , "docker" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Make app.zip
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: dist/app

      - name: Deploy with rsync
        run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./dist/app/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:var/www/test-calltracking/

